name: Build and Deploy
on:
  workflow_dispatch: {}
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
env:
    AWS_REGION: ap-southeast-1
jobs:
  Build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
     
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

        # Install Python Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}

        # Build App and Run Application Test
      - name: Build Application and Run unit Test
        run: python run.py & pytest

  Deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: Build
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v2
        name: Checkout Repository
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          # Assuming the Deployment Group is already setup
          aws deploy create-deployment \
            --application-name PythonWeb \
            --deployment-group-name PythonWebGroup\
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}