name: Build and Deploy
on:
  workflow_dispatch: {}
env:
    AWS_REGION: ap-southeast-1
jobs:
  Build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
     
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

        # Install Python Dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Login AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}

        # Build App and Run Application Test
      - name: Build Application and Run unit Test
        run: python run.py & pytest

  Deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [Build]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          # Assuming the Deployment Group is already setup
          aws deploy create-deployment \
            --application-name WebPython \
            --deployment-group-name WebPythonGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}